### ISSUE TITLE
请问能否出个api版？

### ISSUE THREAD

**Issue by mmmjie** [noneplugin/nonebot-plugin-handle#13]
插件很有趣，群友很爱玩
但猜一次就制图发送，制图频率很高，
但插件又和NB2是同一个进程核心的，人多很容易导致单核被跑满，nb变的卡卡的。

**Comment by MeetWq** [comment]
你试试这样改之后还卡不卡 https://github.com/noneplugin/nonebot-plugin-handle/pull/14

**Comment by mmmjie** [comment]
感谢调整

卡顿的情况似乎有好转，最近几天看几次占用百分比，NB没有像之前一样长时间100%跑满单核

但我无法科学的区分，具体是不是这个原因导致的，还只是碰巧我看的时候没遇到

**Comment by mmmjie** [comment]
> 你试试这样改之后还卡不卡 #14

感谢调整

卡顿的情况似乎有好转，最近几天看几次占用百分比，NB没有像之前一样长时间100%跑满单核

但我无法科学的区分，具体是不是这个原因导致的，还只是碰巧我看的时候没遇到
