### ISSUE TITLE
能否换一个小点的中文字体

### ISSUE THREAD

**Issue by bridgeL** [noneplugin/nonebot-plugin-handle#5]
https://github.com/noneplugin/nonebot-plugin-handle/blob/main/nonebot_plugin_handle/resources/fonts/SourceHanSerifSC-Regular.otf

目前这个23M也太惊人了

**Comment by MeetWq** [comment]
因为这个字体开源而且比较全
你有什么推荐的字体吗

**Comment by bridgeL** [comment]
好吧，我只是单纯考虑让插件小一些，毕竟很多生僻字其实并不在handle的出题范围中，如果牺牲这些生僻字，换一个包含字符少一点的中文，这样会小很多吧
