### ISSUE TITLE
黄字标记数量有误

### ISSUE THREAD

**Issue by Sevenyine** [noneplugin/nonebot-plugin-handle#8]
![IMG_4062](https://github.com/noneplugin/nonebot-plugin-handle/assets/65720409/c87388d9-389e-49af-b8f0-e13219e9f267)
如图，答案是足不出户，**z**u **b**u **ch**u **h**u
但是在前面猜huhuhuhu的时候一个正确的标记为绿色，剩下的三个h就不应该是黄色而是灰色。
按照 AllanChain/chinese-wordle 的规则，若猜对但不在同一位置，应该标记为黄色，至多着色n次。同时，因为猜对了，成语没有其他的h作为声母，所以剩下的不应着色。
规则截图如下：
<img width="838" alt="image" src="https://github.com/noneplugin/nonebot-plugin-handle/assets/65720409/8d1a6282-373e-43eb-95ec-ad1c2275a8a3">

**Comment by MeetWq** [comment]
已修复，目前黄色不会重复出现
