### ISSUE TITLE
【功能建议】能否支持色弱模式

### ISSUE THREAD

**Issue by salspica** [noneplugin/nonebot-plugin-handle#9]
和群友玩的时候有个群友是色弱分辨不了青色玩不了
想问问能不能支持自定义配色（或者调整明度饱和度之类的）

**Comment by MeetWq** [comment]
原 handle https://handle.antfu.me/ 有个“色彩增强”，你看是否符号需求

**Comment by MeetWq** [comment]
自定义配色感觉会比较乱，我想还是预设一些配色

**Comment by salspica** [comment]
![T)Y(@4(B@9`DWJ{`)BD42HY](https://github.com/noneplugin/nonebot-plugin-handle/assets/116940127/65e5e468-1716-4727-947d-f81316b5f694)
群友反馈可以分辨，感谢！
我觉得要预设配色的话这个玫红配绿色就不错，应该是各种类型的色盲色弱人群都适用的，
参考资料：https://baijiahao.baidu.com/s?id=1741486433335878785&wfr=spider&for=pc

**Comment by MeetWq** [comment]
加了色彩增强的配置项

**Comment by salspica** [comment]
再次感谢！已完美适配！
